#!/usr/bin/env bash
# displays information about subdomains

dns_info ()
{
src=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION" | tail -n 1)
echo "$2 $src" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ $# -eq 1 ]
then
  dns_info "$1" "www"
  dns_info "$1" "lb-01"
  dns_info "$1" "web-01"
  dns_info "$1" "web-02"
elif [ $# -eq 2 ]
then
  dns_info "$1" "$2"
fi
