#!/usr/bin/env bash
# Commands used to fix an error preventing 
# connection to port 80 of the server
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
