#!/usr/bin/env bash
#Configure SSH client to connect to a server without password
Host *
  PasswordAuthentication no
  HashKnownHosts yes
  SendEnv LANG LC_*
  GSSAPIAuthentication yes
  GSSAPIDelegateCredentials no
  IdentityFile ~/.ssh/school
